1. One Dimensional Array
A one-dimensional array is a type of linear array.

In [3]:
import numpy as np
a =[1,2,3,4,5]
arr = np.array(a)

print("List in Python: ", a)
print("NumPy Array in Python: ", arr)
print("Type of List:", type(a))
print("Type of NumPy Array:", type(arr))

List in Python:  [1, 2, 3, 4, 5]
NumPy Array in Python:  [1 2 3 4 5]
Type of List: <class 'list'>
Type of NumPy Array: <class 'numpy.ndarray'>


2. Multi-Dimensional Array
A Multi-Dimensional Array is an array that can store data in more than one dimension such as rows and columns. In simple terms it is a array of arrays.

For example a 2D array is like a table with rows and columns where each element is accessed by two indices: one for the row and one for the column. Higher dimensions like 3D arrays involve adding additional layers.

In [4]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]

multi_Dim_array = np.array([list1,
                            list2,
                            list3])

print("This Multidimentional Array: \n", multi_Dim_array)

This Multidimentional Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Parameters of a Numpy Array

1. Axis: Axis of an array describes the order of the indexing into the array.
Axis 0 = one dimensional   --> operate vertically/down rows
Axis 1 = Two dimensional   --> operate horizontally/across columns
Axis 2 = Three dimensional 

Axis represents the direction along which an operation is performed in a multidimensional array.
Axis 0 operates vertically across rows, Axis 1 horizontally across columns in 2D arrays.


In [ ]:
arr = [
 [1, 2, 3],
 [4, 5, 6]
]
print(np.sum(arr, axis=0)) #[5(1+4) 7(2+5) 9(6+3)]
print(np.sum(arr, axis=1)) #[6(1+2+3) 15(4+5+6)]

[5 7 9]
[ 6 15]


In [11]:
#2. Shape: Number of elements along with each axis and is returned as a tuple.

numPy_array = np.array([[1,2,3,1],
                        [2,6,7,2],
                        [3,6,7,3],
                        [4,6,7,4],
                        [5,6,7,5],])
print("Shape of the Array: ", numPy_array.shape)

Shape of the Array:  (5, 4)


4. Data type objects (dtype): Data type objects (dtype) is an example of numpy.dtype class. It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

In [13]:
array1 = np.array([1,2,3])
array2 = np.array([2.3, 5.6, 11])
array3 = np.array(["a", "b"])

print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

int64
float64
<U1


**# Different Ways of Creating Numpy Array**

In [ ]:
#1. numpy.array(): Numpy array object in Numpy is called ndarray. We can create ndarray using this function.
#Syntax: np.array(parameter)
arr1 = np.array([1,2,3,4,5])
print("Method 1: ", arr1)


#2. numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.
# Syntax: np.fromiter(iterable, dtype, count=-1)
var = "NitinPatil"
arr2 = np.fromiter(var, dtype='U2')
print("Method 2: ", arr2)

#3. numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.
# Syntax:  numpy.arange( start , stop, step , dtype=None )
arr3 = np.arange(3, 22, 3, dtype= np.float32)
print("Method 3: ", arr3)



Method 1:  [1 2 3 4 5]
Method 2:  ['N' 'i' 't' 'i' 'n' 'P' 'a' 't' 'i' 'l']
Method 3:  [ 1.  4.  7. 10. 13. 16. 19.]


array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)