In [26]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("--------------------")

#print(arr[[1]])
#print(arr[[0,2]])
print("--------------------")
print(arr[:2, :2])  # first 2 rows, first 2 columns



[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
--------------------
[[1 2]
 [4 5]]


In [32]:
import numpy as np

arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]], [[50, 65, 8], [70, 85, 10], [11, 22, 33]]])
print("Array:")
print(arr)
print("--------------------------------------")

print("Accessed Rows:\n",arr[:,[0]])  #"Accessed Rows:"
print("---------------------")
print(arr[:,[1,2]])



Array:
[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]]
--------------------------------------
Accessed Rows:
 [[[10 25 70]]

 [[50 65  8]]]
---------------------
[[[30 45 55]
  [20 45  7]]

 [[70 85 10]
  [11 22 33]]]
