In [25]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("--------------------")

#print(arr[[1]])
#print(arr[[0,2]])
print("--------------------")
print(arr[:1, :1])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
--------------------
[[1]]
